### ISSUE TITLE
error in MATCH RATES BASED ON ORIGINAL DATA

### ISSUE THREAD

**Issue by sfirke** [adamMaier/reviewr#1]
Sorry this isn't a minimal reproducible example - just jotting it down mid-analysis.  I can share the data w/ you privately if helpful.

The description below is correct at first, there are 794 records in master, 546 in all_matched, and all 546 match (there are 7 duplicates, increasing the resulting number of records to 801).  I think this statement is inaccurate: "68.8% Percent of rows from right matched."  I think that should be 100%?

```
> full_join_qc(master, all_matched)
Joining, by = "applicant_id"

This was a ONE TO MANY join

MATCH DISTRIBUTION IN JOINED DATA
546 (68.2%) Rows are matches
255 (31.8%) Rows are from left only
0 (0%) Rows are from right only

MATCH RATES BASED ON ORIGINAL DATA
67.9% Percent of rows from left matched
68.8% Percent of rows from right matched

ADDITIONAL ROWS
7 More rows with a matched ID than original left
0 More rows with a matched ID than original right
```

**Comment by adamMaier** [comment]
Thanks, Sam. You're right. The code was mistakenly using the number of rows in the left as the denominator in that calculation. Just committed a fix. (In the future I'll learn to close the issue via commit messages... learning as I go!)

Also, as an semi-related FYI, If you re-install the package the join_qc functions are now also usable in pipes.
