### ISSUE TITLE
don't "import" dplyr and rlang 

### ISSUE THREAD

**Issue by sfirke** [adamMaier/reviewr#2]
You have them `import` in your NAMESPACE.  Which I think allows you to program with those functions without specifying their namespace like `dplyr::filter()`.  But, I think it also puts all their functions in the environment for the user.

When this package is loaded, it loads rlang, and then warns "the following objects are masked from package:purrr" and lists many functions.  I think it's effectively doing `library(rlang)` because of the `import`.

**Comment by adamMaier** [comment]
Thanks, Sam. I'll take a look. At the time, I put `rlang` in the `import` because I had trouble successfully assigning its prefix on some of the built in operators, like `!!`.  I know that's the motivation, but I might now be able to accommodate that in the functions.

**Comment by adamMaier** [comment]
Thanks again, Sam. I ended up just importing !! and := from `rlang `and removing `rlang `and `dplyr `from my imports. For whatever reason, I had trouble with using `rlang::':='()` in my code so need to import for now.
